// Create a list and add elements to it in one step
List<String> fruits = new List<String> {'apple','orange','banana','peach'};
//System.debug('Printing all fruits inside of the list : '+fruits);
// Add elements to a list after it has been created
List<String> AddMoreFruits = new List<String>();
AddMoreFruits.add('grape');
AddMoreFruits.add('pineapple');
System.debug('Printing fruits just addded : '+AddMoreFruits);